### ISSUE TITLE
Campanha

### ISSUE THREAD

**Issue by vitornuness** [VitorNuness/checkout-inteligente-back#1]
- [Repositório](https://github.com/VitorNuness/checkout-inteligente-back)
- Criar uma branch "feature/campaign" e realizar as seguintes alterações

- [x] Refatorar os métodos do CampaignController
    - [x] Método Index deve ser assíncrono e remover sort como parâmetro 
    - [x] Método Show deve ser assíncrono e remover sort como parâmetro
    - [x] Método Store deve receber o nome da campanha e uma imagem que pode ser nula
    - [x] Método Update deve receber o id, nome da campanha e uma imagem que pode ser nula
    - [x] Método Delete deve receber o id

Seguir exemplo dos métodos referentes ao produto.

**Comment by MayconMacedo23** [comment]
Ali no Campaign Repository eu tirei o void @VitorNuness , procurei aqui e no chatgpt tmb, disse aqui, pra não usar o void

"Usar Task (ou Task<T>) em vez de void em métodos assíncronos é a prática recomendada, porque:

Permite controle: O chamador pode aguardar o método assíncrono e garantir que ele foi concluído.
Exceções são capturadas: Se uma exceção ocorrer, ela pode ser tratada adequadamente, seja no método de chamada ou com um bloco try-catch.
Facilidade de teste: Métodos que retornam Task são mais fáceis de testar, pois podem ser aguardados em testes unitários, permitindo validação do comportamento assíncrono.****

**Comment by vitornuness** [comment]
Isso aí! Esta certo.

**Comment by vitornuness** [comment]
@MayconMacedo23 Faz aquele merge que o Alex e o Vinicius estavam fazendo em sala pra branch dev, que eu consigo análisar o código.
